### ISSUE TITLE
Add a section of "Success stories" on the start page

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#174]
**Description:**
We would like to display a number of success stories through Just Arrived in order to show what we have done historically. Just a few cases would be enough, 3-4 probably. I am thinking that it should be displayed both for logged in and not logged in users, let's discuss it before starting on this assignment so everything is clear

**Comment by tikkat** [comment]
@andrew-hawari let me know when you have time to discuss this one, it would be good if we could have a small discussion around it and decide what it would mean in practice to add such a section

**Comment by andrew-hawari** [comment]
@tikka Hej 
kan vi prata om det? :)

**Comment by buren** [comment]
I like this a lot 👍this data should not be hardcoded in this (just-match-web) code base. The API feels like a better fit, since then we can reuse that on our website and other places. However I'm not sure we want the API to become a CMS either.. 🤔I've looked at Voog for CMS (they also have translation support) but implementing/integrating it will require some effort..
