### ISSUE TITLE
Profile image upload, LMA card and other file uploads are not working

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#197]
**Comment:**
It is not possible to upload a profile image or the other work documents, at least not in lastest Chrome on OSX. 

![image](https://cloud.githubusercontent.com/assets/3510315/22518618/8715ec34-e8ad-11e6-8ce7-e137d48a82f2.png)

![image](https://cloud.githubusercontent.com/assets/3510315/22518666/b636e338-e8ad-11e6-88a3-a2740597e698.png)

**Update:**
I tried it again now and it seems to be working correctly now. It did not however during the test session, might there be some other problem here? Let's investigate this!

**Comment by tikkat** [comment]
@bex1 @buren Maybe the frontend was waiting for a response from the backend and therefore didn't give me any feedback in the frontend? As a user I couldn't see any change at all and I assumed that it didn't work. If this is the case we would like to add some kind of loading indication or similar maybe?

**Comment by bex1** [comment]
They do work, so a loading gif will solve it
@tikkat

**Comment by Ekman1991** [comment]
@bex1: This is still not working. See error message I get when trying to upload below:

[Error] Failed to load resource: the server responded with a status of 422 (Unprocessable Entity) (images, line 0)

**Comment by Ekman1991** [comment]
[Error] Failed to load resource: the server responded with a status of 422 (Unprocessable Entity) (images, line 0) is due to unsupported file formats. Checked the back-end. Supported file formats for images are .png .jpeg and .gif.

This should be solved by outputting a error message saying "Wrong file format" and perhaps a loading gif aswell giving feedback to the user that they are uploading an image
