### ISSUE TITLE
Can't add English to user language if chosen as default language 

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#285]
On the user profile page I can try choose English under "Other languages" if I've chosen it as the default language.

Its displayed in the dropdown menu but nothing happens if I chose it (other languages work fine).

**Comment by bellevik** [comment]
@buren Could you explain a bit more about the issue? I have chosen English as the "Default language" and can still choose (and save) English as a language under "Other language skills". However if I choose a language as my "Native language" I can't add it under "Other language skills", is that the issue? In that case, is that an issue or a "feature", since I guess we can assume that one is very proficient at their native language? Otherwise, I guess I'm misunderstanding the issue :)

**Comment by bex1** [comment]
The native language can not be chosen among other language skills since a native language is a language skill with proficiency 5. When selecting other language skills one can choose one of the other 4 levels. This is so you may only have one native language.
