### ISSUE TITLE
Sometimes if logged in the start page renders a blank page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#288]
<img width="1428" alt="screen shot 2017-02-14 at 09 35 11" src="https://cloud.githubusercontent.com/assets/922411/22921198/f3062edc-f298-11e6-9120-be1a0addf7cc.png">

⚠️ Please note the error message in the console. The app is trying to fetch a token which isn't there anymore (perhaps I logged out and we don't clear the local token but IDK).

**Comment by bellevik** [comment]
The only way I can seem to recreate this issue is by manually deleting/modifying the authtoken during a session and then reloading the page. I've tried using private browsing and privacy badger and of course logging in and out a number of times. I've also tried clearing local storage and cookies during a session followed by both reloading the page and logging out and in again. None of these other scenarios lead to that issue.
