### ISSUE TITLE
[Spike] Test Angular Material

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#311]
Before we make any final descisions whether to go with Angular Material we need to try/test a few things.

1. Firstly we need to check so that the total bundle doesn't get too large (we're already at ~1MB!).
2. Secondly try to gain some understanding of how much time it would take to implement.
3. Thirdly we need to decide on what to do with bootstrap, we're mainly using bootstraps grid (and some alerts). Should we completely 🔪 Bootstrap, phase it out, or just keep the grid parts.

**Comment by bex1** [comment]
1. I will look into this.
2. I will look into this.
3. Im all for 🔪 bootstrap completely. Already begun phasing out most bootstrap classes throughout the html and replacing with proper scss. This gives us more control.

Additionally since there are only a few components available that we might want from Angular 2 Material, Im not yet sure that it is worth it. We could make our own components, which also would give us more control and fewer dependencies.

**Comment by bex1** [comment]
http://www.primefaces.org/primeng/#/
https://ng-semantic.herokuapp.com/#/

Please take a look at these.
Open source.
A much wider range of components.
@buren @tikkat
