### ISSUE TITLE
Potential bug where its not possible to save Work experience or General skills text

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#321]
Its possible to save the form, however the text isn't updated...

**Comment by bex1** [comment]
This worked earlier so something must have changed in the API.
The data is passed to fields competence_text and job_experience but those are not saved in the API anymore.
Since the user is edited the user is replaced with the user after the UPDATE, which keeps the old fields since they were not updated properly
@buren

**Comment by bex1** [comment]
This has been solved.
It was a client-side bug

**Comment by buren** [comment]
🙇
