### ISSUE TITLE
New profile page that can be viewed by others

### ISSUE THREAD

**Issue by bex1** [justarrived/just-match-web#456]
It will be redesigned into something like below:

Using modals for editing if logged in as that user.

![image](https://cloud.githubusercontent.com/assets/3455771/25383077/b2a7eee4-29ba-11e7-935a-a788448208a9.png)

**Comment by buren** [comment]
👍 To complete this feature we need another field, `public_profile`, returned from `/users/:id`. I don't think our profiles should be public by default (especially since they aren't now.. could be quite the chock for our existing users 😉).

BTW, really like that this would allow users to edit their profiles in a more WYSIWYG-like fashion 👍

**Comment by bex1** [comment]
Agreed. They should initially be able "publish profile" to be able to share it with others. Then we can transition towards default public profiles in time.

**Comment by buren** [comment]
💤
